version: '3'

services:
  y_chits:
    image: arunawsdevops/ychits
    container_name: y_chits
    build:
      context: /home/ec2-user/YCHITS
      dockerfile: Dockerfile
    ports:
      - "1003:1001"
    depends_on:
      - mongodb1
    networks:
      - app_network

  mongodb1:
    image: mongo
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - ../../data:/data/db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

